services:
  - type: web
    name: smartvenue-backend
    runtime: java
    rootDir: backend/smartvenue
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
