spring.application.name=smartvenue

# ==========================
# Database Configuration
# ==========================
spring.datasource.url=${gateway01.ap-southeast-1.prod.aws.tidbcloud.com}
spring.datasource.username=${2AWzz5y6B2BrBKt.root}
spring.datasource.password=${0FVJZWj6Dy9jgKLz}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================
# Server Configuration
# ==========================
server.port=${PORT:8080}